export const doctors = [
    {
      id: 1,
      name: "Dr. Divyesh Parmar(me)",
      image: "/d1.png",
      gender: "Male" ,
      specialty: "Dermatologist",
      experience: "11",
      location: "Mumbai",
      fee: "800",
      rating: 97,
      reviews: 159,
      availability: "",
      clinicName: "",
      additionalClinics: 0,
    },
    {
      id: 2,
      name: "Dr. Anjali Sharma",
      image: "/d2.png",
      gender: "Female",
      specialty: "Cardiologist",
      experience: "8",
      location: "Gujarat",
      fee: "1200",
      rating: 93,
      reviews: 102,
      availability: "Available Today",
      clinicName: "",
      additionalClinics: 1,
    },
    {
      id: 3,
      name: "Dr. Ravi Mehta",
      image: "/d3.png",
      gender: "Male" ,
      specialty: "Dermatologist",
      experience: "15",
      location: "Mumbai",
      fee: "1000",
      rating: 95,
      reviews: 178,
      availability: "",
      clinicName: "",
      additionalClinics: 2,
    },
    {
      id: 4,
      name: "Dr. Sneha Iyer",
      image: "/d5.png",
      gender: "Female",
      specialty: "Gynecologist",
      experience: "7 ",
      location: "Delhi",
      fee: "700",
      rating: 89,
      reviews: 64,
      availability: "",
      clinicName: "Urban Roots Health Hub",
      additionalClinics: 0,
    },
    {
      id: 5,
      name: "Dr. Ajay Kumar",
      image: "/d4.png",
      gender: "Male" ,
      specialty: "Neurologist",
      experience: "12",
      location: "Delhi",
      fee: "1500",
      rating: 96,
      reviews: 144,
      availability: "Available Today",
      clinicName: "WellCare Medical Center",
      additionalClinics: 1,
    },
    {
      id: 6,
      name: "Dr. Radhika Verma",
      image: "/d2.png",
      gender: "Female",
      specialty: "Dermatologist",
      experience: "6",
      location: "Gujarat",
      fee: "850",
      rating: 91,
      reviews: 88,
      availability: "",
      clinicName: "",
      additionalClinics: 0,
    },
    {
      id: 7,
      name: "Dr. Nikhil Reddy",
      image: "/d3.png",
      gender: "Male" ,
      specialty: "Neurologist",
      experience: "7",
      location: "Mumbai",
      fee: "950",
      rating: 87,
      reviews: 73,
      availability: "",
      clinicName: "Lifepoint Family Clinic",
      additionalClinics: 0,
    },
    {
      id: 8,
      name: "Dr. Priya Desai",
      image: "/d5.png",
      gender: "Female",
      specialty: "Gynecologist",
      experience: "14",
      location: "Gujarat",
      fee: "1100",
      rating: 94,
      reviews: 132,
      availability: "",
      clinicName: "",
      additionalClinics: 1,
    },
    {
      id: 9,
      name: "Dr. Arvind Patel",
      image: "/d4.png",
      gender: "Male" ,
      specialty: "Gynecologist",
      experience: "4",
      location: "Delhi",
      fee: "600",
      rating: 88,
      reviews: 49,
      availability: "Available Today",
      clinicName: "",
      additionalClinics: 0,
    },
    {
      id: 10,
      name: "Dr. Meena Raju",
      image: "/d2.png",
      gender: "Female",
      specialty: "Neurologist",
      experience: "11",
      location: "USA",
      fee: "1300",
      rating: 90,
      reviews: 95,
      availability: "",
      clinicName: "Serenity Health Clinic",
      additionalClinics: 2,
    },
    {
      id: 11,
      name: "Dr. Ankit Shah",
      image: "/d1.png",
      gender: "Male" ,
      specialty: "Dermatologist",
      experience: "8",
      location: "Gujarat",
      fee: "1000",
      rating: 92,
      reviews: 110,
      availability: "",
      clinicName: "GlowCare Skin Clinic",
      additionalClinics: 1,
    },
    {
      id: 12,
      name: "Dr. Priya Menon",
      image: "/d5.png",
      gender: "Female",
      specialty: "Pediatrician",
      experience: "7",
      location: "Delhi",
      fee: "800",
      rating: 89,
      reviews: 78,
      availability: "Available Today",
      clinicName: "BrightFuture Kids Clinic",
      additionalClinics: 0,
    },
    {
      id: 13,
      name: "Dr. Ravi Deshmukh",
      image: "/d3.png",
      gender: "Male" ,
      specialty: "Cardiologist",
      experience: "12",
      location: "Mumbai",
      fee: "1500",
      rating: 95,
      reviews: 143,
      availability: "",
      clinicName: "Heartline Cardiac Center",
      additionalClinics: 2,
    },
    {
      id: 14,
      name: "Dr. Sandra Thomas",
      image: "/d2.png",
      gender: "Female",
      specialty: "Psychiatrist",
      experience: "10",
      location: "USA",
      fee: "1200",
      rating: 91,
      reviews: 98,
      availability: "",
      clinicName: "MindWell Mental Health",
      additionalClinics: 1,
    },
    {
      id: 15,
      name: "Dr. Karan Patel",
      image: "/d1.png",
      gender: "Male" ,
      specialty: "Orthopedic",
      experience: "6",
      location: "Gujarat",
      fee: "900",
      rating: 88,
      reviews: 67,
      availability: "Available Today",
      clinicName: "Hearing & Voice Clinic",
      additionalClinics: 0,
    },
    {
      id: 16,
      name: "Dr. Neha Chopra",
      image: "/d5.png",
      gender: "Female",
      specialty: "Orthopedic",
      experience: "11 ",
      location: "Delhi",
      fee: "1100",
      rating: 93,
      reviews: 112,
      availability: "",
      clinicName: "OrthoPlus Bone Care",
      additionalClinics: 1,
    },
    {
      id: 17,
      name: "Dr. Emily Star",
      image: "/d2.png",
      gender: "Female" ,
      specialty: "Gynecologist",
      experience: "7",
      location: "Mumbai",
      fee: "950",
      rating: 90,
      reviews: 89,
      availability: "Available Today",
      clinicName: "Women's Wellness Center",
      additionalClinics: 0,
    },
    {
      id: 18,
      name: "Dr. Emily George",
      image: "/d5.png",
      gender: "Female",
      specialty: "Gynecologist",
      experience: "3",
      location: "USA",
      fee: "700",
      rating: 85,
      reviews: 52,
      availability: "",
      clinicName: "PrimeCare Family Clinic",
      additionalClinics: 0,
    },
    {
      id: 19,
      name: "Dr. Vikas Tyagi",
      image: "/d4.png",
      gender: "Male",
      specialty: "Dermatologist",
      experience: "9",
      location: "Delhi",
      fee: "1050",
      rating: 92,
      reviews: 99,
      availability: "",
      clinicName: "DermaGlow Skin Center",
      additionalClinics: 2,
    },
    {
      id: 20,
      name: "Dr. Aarti Joshi",
      image: "/d2.png",
      gender: "Female",
      specialty: "Neurologist",
      experience: "14",
      location: "Gujarat",
      fee: "1600",
      rating: 94,
      reviews: 134,
      availability: "Available Today",
      clinicName: "NeuroCare Brain & Spine",
      additionalClinics: 1,
    },
  ];
  